import axios from "axios"
import { useEffect, useState } from "react"
import Head from 'next/head'


function users() {
    const [details, setDetails] = useState([]);
    const [transfer, setTransfer] = useState(false);
    const [sender, setSender] = useState("")
    const [reciever, setReciever] = useState("")
    const [amount, setAmount] = useState()


    useEffect(() => {
        axios.get("http://localhost:4000/getdetails")
            .then((res) => {
                // console.log(res.data);
                setDetails(res.data);
            })
    }, [])

    function handleClick() {
        setTransfer(!transfer);
    }

    function mapFunc(detail) {
        return (
            <div className="detailbody">
                <span><img src={detail.photo} alt="img" /></span>
                <span>Username- {detail.username} </span>
                <span>Balance-{detail.accBalance} </span>
            </div>
        )
    }

    function btnClk() {
        if (sender === "" || reciever === "" || amount === undefined) {
            alert("Please fill required fields")
            return;
        }
        if (isNaN(amount) || amount <= 0) {
            alert("Amount must be a positive Number.")
            return;
        }
        if (sender === reciever) {
            alert("Sender and reciever must be different.")
            return;
        }
        axios.get("http://localhost:4000/getdetails")
            .then((res) => {
                const giver = res.data.filter(user => {
                    return user.username === sender;
                });
                const taker = res.data.filter(user => {
                    return user.username === reciever;
                })
                if (giver.length === 0 || taker.length === 0) {
                    alert("User not found.");
                    return;
                }

                if (giver[0].accBalance < amount) {
                    alert(giver[0].username + " don't have enough balance.");
                    return;
                }

                axios.post("http://localhost:4000/transfermoney", { sender, reciever, amount })
                window.location.reload(true);
                alert("Transfer successfull.")
            })
        // console.log(sender, reciever);

    }

    return (
        <div className="users">
            <Head>
                <title>Banking Site</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/my_logo.jpeg" />
            </Head>
            <button className="transfer" onClick={handleClick}> Transfer Money</button>
            {transfer &&
                <div className="transferport">
                    <input type="text" autoFocus onChange={(e) => { setSender(e.target.value) }} name="sender" value={sender} placeholder="sender username" />
                    <input type="text" onChange={(e) => { setReciever(e.target.value) }} name="reciever" value={reciever} placeholder="reciever username" />
                    <input type="text" onChange={(e) => { setAmount(e.target.value) }} name="amount" value={amount} placeholder="Amount" />
                    <input onClick={btnClk} className="btnsend" type="button" value="send" />
                </div>
            }
            <div className="details">


                {details.length != 0 && details.map(mapFunc)}
            </div>

        </div>
    )
}

export default users

